backend:
  name: github
  repo: dumpeldown/jessemail
  branch: main
  site_id: starlit-crepe-097817.netlify.app

media_folder: "src/assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "gr20"
    label: "GR20 Journal"
    folder: "src/gr20"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
